Add verbose output to stream info and info cmd to example client
scottlamb/retina pull request #49
Opened 2022-01-10 16:05 UTC by kodx

Add verbose output to stream info and info command to example client.
README update.

2022-01-10 17:08 UTC, scottlamb reviewed
Thanks for the PR!

Could you please run `cargo fmt`?

I'm curious why you added a `Display` impl to `Stream` rather than using `Debug`. I just ran them side-by-side and the biggest difference I saw was that the `control` URL printing is ugly/verbose in `Debug`; was that it?

I confess that I'm afraid I'll forget to add new things to the `Display` impl. I'm tempted to use [`custom_derive`](https://crates.io/crates/custom-derive) to that single field's `Debug` output without messing with the others, but it's probably not worth the extra dependency.

2022-01-10 17:08 UTC, scottlamb commented on src/client/mod.rs
> +            "  RTP payload time: {}\n",
typo? s/time/type/

2022-01-10 17:25 UTC, kodx commented on src/client/mod.rs
> +            "  RTP payload time: {}\n",
I'm writing a client implementation with retina and add this to ease development and debug, for this purpose added an info command to example client.  
> I just ran them side-by-side and the biggest difference I saw was that the control URL printing is ugly/verbose in Debug; was that it?

Yes and for less clutter output.

> `"  RTP payload time: {}\n",`

`time` is typo here, should be `type`, will fix it.

I'm a newbie rust developer and glad to hear how this can be done in a proper way.

2022-01-10 18:08 UTC, scottlamb commented
> I'm writing a client implementation with retina and add this to ease development and debug, for this purpose added an info command to example client.

Cool!

> I'm a newbie rust developer and glad to hear how this can be done in a proper way.

I'd say it's more subjective than "proper" or not. I'm asking because:

1. when I have two places to update something (there are several of these in Retina already), I sometimes forget to keep them in sync when the compiler doesn't remind me, and especially when they're further apart. E.g. if I add a field to `UdpSockets`, I might forget to add it to the `Display` impl on `Stream` (a different type).
2. if I don't know why you've made the output how you have, I'll accidentally change it a way you won't like when I'm refactoring later.

How does this sound: a custom `Debug` impl that's as near the `struct` definition in the source code as possible:

```rust
struct Stream { /* ... */ }

impl std::fmt::Debug for Stream {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        f.debug_struct("Stream")
         // ...
         .field("control", &self.control.as_ref().map(Url::as_str))
         // ...
         .finish()
    }
}
```

and if you want to tweak the output on `UdpSockets`, do that in its `Debug` impl rather than having Stream jump over that layer. This way I'm more likely to maintain it well.

2022-01-11 19:45 UTC, kodx commented
> > I'm writing a client implementation with retina and add this to ease development and debug, for this purpose added an info command to example client.
> 
> Cool!
> 
> > I'm a newbie rust developer and glad to hear how this can be done in a proper way.
> 
> I'd say it's more subjective than "proper" or not. I'm asking because:
> 
>     1. when I have two places to update something (there are several of these in Retina already), I sometimes forget to keep them in sync when the compiler doesn't remind me, and especially when they're further apart. E.g. if I add a field to `UdpSockets`, I might forget to add it to the `Display` impl on `Stream` (a different type).
> 
>     2. if I don't know why you've made the output how you have, I'll accidentally change it a way you won't like when I'm refactoring later.
> 
> 
> How does this sound: a custom `Debug` impl that's as near the `struct` definition in the source code as possible:
> 
> ```rust
> struct Stream { /* ... */ }
> 
> impl std::fmt::Debug for Stream {
>     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
>         f.debug_struct("Stream")
>          // ...
>          .field("control", &self.control.as_ref().map(Url::as_str))
>          // ...
>          .finish()
>     }
> }
> ```
> 
> and if you want to tweak the output on `UdpSockets`, do that in its `Debug` impl rather than having Stream jump over that layer. This way I'm more likely to maintain it well.

Rewrite to Debug impl, please review.

2022-01-11 23:40 UTC, scottlamb commented on src/lib.rs
> +pub fn fmt_option<T>(opt: &Option<T>) -> String
One last nit: I don't want to add this to the crate's public API.

I'm not sure it's necessary at all anymore: iirc there's an implied `impl<T: Debug> Debug for Option<T>`. You might try getting rid of it; but I'm fine if you just remove the `pub`.

2022-01-11 23:42 UTC, scottlamb requested changes
One last nit; looks good otherwise. Thanks for the changes to accommodate my preferences for maintenance.

2022-01-12 16:22 UTC, scottlamb approved these changes

2022-01-12 16:22 UTC, merged